version: "3.8"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: dockerfile
    
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    restart: always
    tty: true
    networks:
      dokidoki_net:
        ipv4_address: 172.20.128.3


  database_redis:
    container_name: database_redis
    image: redis
    command: ["redis-server", "--appendonly", "yes", "--replica-read-only", "no","--requirepass", "qhBb3Ht7Psvz54PCjlAw"]
    networks:
      - dokidoki_net
    restart: always

  api-gateway-server:
    container_name: api-gateway-server
    build:
      context: ./backend/api-gateway
      dockerfile: dockerfile
    restart: always
    stdin_open: true
    tty: true
    networks:
      dokidoki_net:
        ipv4_address: 172.20.128.4


  bid-server:
    container_name: bid-server
    build:
      context: ./backend/bid
      dockerfile: dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/dokidb?serverTimezone=UTC&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: dokidoki
      SPRING_DATASOURCE_PASSWORD: dokidoki202
      SPRING_REDIS_HOST: database_redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: qhBb3Ht7Psvz54PCjlAw
    restart: always
    networks:
      - dokidoki_net

  auction-server:
    container_name: auction-server
    build:
      context: ./backend/auction
      dockerfile: dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/dokidb?serverTimezone=UTC&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: dokidoki
      SPRING_DATASOURCE_PASSWORD: dokidoki202
    restart: always
    networks:
      - dokidoki_net

  user-server:
    container_name: user-server
    build:
      context: ./backend/user-server
      dockerfile: dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/dokidb?serverTimezone=UTC&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: dokidoki
      SPRING_DATASOURCE_PASSWORD: dokidoki202
    restart: always
    networks:
      - dokidoki_net

networks:
  dokidoki_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24