spring:
  # database local
  datasource:
    url: jdbc:mysql://localhost:3306/dokidoki
    username: root
    password: root

    jpa:
      hibernate:
        ddl-auto: create
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.MySQL8Dialect
    logging:
      level:
        org.hibernate.type: trace

oauth2:
  google:
    client_id: 409728357789-pfbb5h8u9m4tib34v3qne7n7atat1tbc.apps.googleusercontent.com
    client_secret: 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
    profile_uri: https://www.googleapis.com/oauth2/v3/userinfo
    redirect_uri: http://localhost:8080/oauth2/google/redirect


