
spring:
  datasource:
#    url: jdbc:mysql://j8a202.p.ssafy.io:3306/dokidb?serverTimezone=UTC&characterEncoding=UTF-8
    url: jdbc:mysql://localhost:3306/dokidb?serverTimezone=UTC&characterEncoding=UTF-8
    username: dokidoki
    password: dokidoki202
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

logging:
  level:
    root: debug

cloud:
  aws:
    s3:
      bucket: dokidoki
    credentials:
      access-key: AKIAUEVS3DJH3EYUME6G
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

jwt:
  issuer: dokidoki.com
  secret: CEV5lPhLfU3RdjTqoHBfEHNrIWAGDRTZfFSLAO5X
  access_expiration: 3600000
  refresh_expiration: 1296000000