server:
  port: 80

jwt:
  secret: CEV5lPhLfU3RdjTqoHBfEHNrIWAGDRTZfFSLAO5X

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "https://j8a202.p.ssafy.io"
            allow-credentials: true   #추가
            allowedHeaders:
              - x-requested-with
              - authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - POST
              - GET
              - PUT
              - OPTIONS
              - DELETE

      # bid no auth routing
      routes:
      - id: bid-server
        uri: http://bid-server
        predicates:
          - Path=/api/bids/auctions/{auction_id}/initial-info
        filters:
          - RewritePath=/api/bids/(?<segment>.*), /$\{segment}

      # bid auth routing
      - id: bid-server
        uri: http://bid-server
        predicates:
          - Path=/api/bids/**
        filters:
          - RewritePath=/api/bids/(?<segment>.*), /$\{segment}
          - JwtAuthenticationFilter

      # auction no auth routing
      - id: auction-server
        uri: http://auction-server
        predicates:
          - Path=/api/auctions/auction-lists/whole/**, /api/auctions/lists/**, /api/auctions/total-prices, /api/auctions/total-treasury, /api/auctions/products/** , /api/auctions/{auction_id}/leaderboards/**, /api/auctions/most-sale-products
        filters:
          - RewritePath=/api/auctions/(?<segment>.*), /$\{segment}

      # auction auth routing
      - id: auction-server
        uri: http://auction-server
        predicates:
          - Path=/api/auctions/**
        filters:
          - RewritePath=/api/auctions/(?<segment>.*), /$\{segment}
          - JwtAuthenticationFilter

      # # notice routing
      # - id: notice-server
      #   uri: http://notice-server
      #   predicates:
      #     - Path=/api/notices/**
      #   filters:
      #     - RewritePath=/api/notices/(?<segment>.*), /$\{segment}

      # socket routing
      - id: notice-server
        uri: ws://notice-server
        predicates:
          - Path=/api/notices/ws
        filters:
          - RewritePath=/api/notices/(?<segment>.*), /$\{segment}

      # user no auth routing
      - id: user-server
        uri: http://user-server
        predicates:
          - Path=/api/users/oauth2/**, /api/user/tokens/refresh, /api/users/points/super-rich
        filters:
          - RewritePath=/api/users/(?<segment>.*), /$\{segment}

      # user auth routing
      - id: user-server
        uri: http://user-server
        predicates:
          - Path=/api/users/**
        filters:
          - RewritePath=/api/users/(?<segment>.*), /$\{segment}
          - JwtAuthenticationFilter