jwt:
  secret: CEV5lPhLfU3RdjTqoHBfEHNrIWAGDRTZfFSLAO5X

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: '*'
            allowedMethods: '*'
      routes:
      - id: bid-server
        uri: http://bid-server:8081
        predicates:
          - Path=/api/bids/**
        filters:
          - RewritePath=/api/bids/(?<segment>.*), /$\{segment}
          #- JwtAuthenticationFilter

      - id: auction-server
        uri: http://auction-server:8082
        predicates:
          - Path=/api/auctions/**
        filters:
          - RewritePath=/api/auctions/(?<segment>.*), /$\{segment}
          #- JwtAuthenticationFilter

      - id: notice-server
        uri: http://notice-server:8084
        predicates:
          - Path=/api/notices/**
        filters:
          - RewritePath=/api/auctions/(?<segment>.*), /$\{segment}
          #- JwtAuthenticationFilter

      - id: user-server
        uri: http://user-server:8083
        predicates:
          - Path=/api/users/**
        filters:
          - RewritePath=/api/users/(?<segment>.*), /$\{segment}

      - id: user-server
        uri: http://user-server:8083
        predicates:
          - Path=/api/users/**
          - Method=DELETE
        filters:
          - RewritePath=/api/users/(?<segment>.*), /$\{segment}
          #- JwtAuthenticationFilter