jwt:
  secret: CEV5lPhLfU3RdjTqoHBfEHNrIWAGDRTZfFSLAO5X

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - '*'
            allow-credentials: false
            allowedHeaders: '*'
            allowedMethods: '*'
      routes:
      - id: bid-server
        uri: http://172.17.0.1:8081
        predicates:
          - Path=/api/bid/**
        filters:
          - RewritePath=/api/bid/(?<segment>.*), /$\{segment}
          - JwtAuthenticationFilter

      - id: auction-server
        uri: http://172.17.0.1:8082
        predicates:
          - Path=/api/auction/**
        filters:
          - RewritePath=/api/auction/(?<segment>.*), /$\{segment}
          - JwtAuthenticationFilter

      - id: user-server
        uri: http://172.17.0.1:8083
        predicates:
          - Path=/api/user/**
        filters:
          - RewritePath=/api/user/(?<segment>.*), /$\{segment}

      - id: user-server
        uri: http://172.17.0.1:8083
        predicates:
          - Path=/api/user/**
          - Method=DELETE
        filters:
          - RewritePath=/api/user/(?<segment>.*), /$\{segment}
          - JwtAuthenticationFilter